<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [59]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists
def matrix_mul(matrix1, matrix2):
    # write your code
    r1 =len(matrix1)                                             ##len of matrix1
    c1 =len(matrix1[0])                                          ##len of row one of matrix1
    r2 =len(matrix2)                                             ##len of the matrix 2
    c2 =len(matrix2[0])                                          ##len of row one of matrix 2
    
    if(c1!=r2):                                                  ## if length of row1 of matrix 1 is not equal to length of matrix 2
        print("\nNot Possible to Multiply")                      ## then by math multiplication is not possible
        return 0                                                 ## in that case return 0
    else:                                                        
        result =[[0 for j in range(c2)] for i in range(r1)]      ## range(c2)=range(0,length(row1 of matrix2)), range(r1)=range(0,length of matrix1)
        for i in range(r1):                                      ## looping through the range(0,length of matrix1)
            for j in range(c2):                                  ## looping through the range(0,length of length of row1 of matrix2)
                for k in range(r2):                              ## looping through the range(0,length of matrix2)
                    result[i][j] +=matrix1[i][k]*matrix2[k][j]   ## result in the form of [i][j]
        return result                                            ## return the result
    
#matrix_mul(A, B)

In [28]:
A   = [[1, 3, 4],
             [2, 5, 7],
             [5, 9, 6]]
B   = [[1, 0, 0],
             [0, 1, 0],
             [0, 0, 1]]
matrix_mul(A,B)

[[1, 3, 4], [2, 5, 7], [5, 9, 6]]

In [29]:
A   = [[1, 2],
             [3, 4]]
B   = [[1, 2, 3, 4, 5],
             [5, 6, 7, 8, 9]]
matrix_mul(A,B)

[[11, 14, 17, 20, 23], [23, 30, 37, 44, 51]]

In [30]:
A   = [[1, 2],
             [3, 4]]
B   = [[1, 4],
             [5, 6],
             [7, 8],
             [9, 6]]
matrix_mul(A,B)


Not Possible to Multiply


0

<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [60]:
import random
from random import uniform
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    # your code here for picking an element from with the probability propotional to its magnitude
    total_sum=0                                                     ##initializing sum and cumulative sum
    cumulative_sum=[]                                               ##Adding the current value with next value in the list -- Cumulative Sum
    for i in range(len(A)):                                         ##looping through the range of length of list ie, range(0, 10)
        total_sum=total_sum+A[i]                                    ## adding the ith element to the sum
        cumulative_sum.append(total_sum)                            ##appending the sum to cumulative list for every list elements
    print("Total Sum of Elements in the List: ",total_sum)          ##print total_sum
    print("The List is :",A)                                        ##print List A
    print("Cumulative Sum of List is :", cumulative_sum)            ##print Cumulative Sum
    ##randomly choosing a number from sum
    rand_num=int(random.uniform(0,total_sum))                       ##sum is the sum of list, ranodmly choosing a number from 0 to sum
    print("The Random Number Choosen:",rand_num)
    number=0                                                        ##initializing the number
    for index in range(len(cumulative_sum)):                        ##looping through the Index of Cumulative sum list which is a range of (0,10)
        if (rand_num>cumulative_sum[index] and rand_num<cumulative_sum[index+1]):
            return A[index+1]
        
    return number                                                   ##selected_random_number

def sampling_based_on_magnitued():
    for i in range(1,100):                                          ## looping through a range of 100 times
        number = pick_a_number_from_list(A)                         ## pick the number from the list every iteration
        print(number)

        
A=[0, 5, 27, 6, 13, 28, 100, 45, 10, 79]
sampling_based_on_magnitued()

Total Sum of Elements in the List:  313
The List is : [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]
Cumulative Sum of List is : [0, 5, 32, 38, 51, 79, 179, 224, 234, 313]
The Random Number Choosen: 210
45
Total Sum of Elements in the List:  313
The List is : [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]
Cumulative Sum of List is : [0, 5, 32, 38, 51, 79, 179, 224, 234, 313]
The Random Number Choosen: 110
100
Total Sum of Elements in the List:  313
The List is : [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]
Cumulative Sum of List is : [0, 5, 32, 38, 51, 79, 179, 224, 234, 313]
The Random Number Choosen: 252
79
Total Sum of Elements in the List:  313
The List is : [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]
Cumulative Sum of List is : [0, 5, 32, 38, 51, 79, 179, 224, 234, 313]
The Random Number Choosen: 177
100
Total Sum of Elements in the List:  313
The List is : [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]
Cumulative Sum of List is : [0, 5, 32, 38, 51, 79, 179, 224, 234, 313]
The Random Number Choosen: 67
28
Total Sum

<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [61]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(string):
    # write your code
    given_string=string                  ## given string
    print("Given String:",given_string)  ##print the given string
    new_string=''                        ##initialize the new string
    for char in given_string:            ##looping through the charecters in the string
        if char.isdigit():               ##if the char is digit, then replace that value with the # symbol
            new_string+="#"              ##replace with "#"
        else:
            pass
        
    return new_string                    ##return the new string


In [62]:
string="abc"
replace_digits(string)

Given String: abc


''

In [63]:
string="234"
replace_digits(string)

Given String: 234


'###'

In [64]:
string="a2b3c4"
replace_digits(string)

Given String: a2b3c4


'###'

In [65]:
string="#2a$#b%c%561#"
replace_digits(string)

Given String: #2a$#b%c%561#


'####'

In [41]:
##solution
import re

def replace_char(string):
    replacements=[("\D",""),("\d","#")]
    for old,new in replacements:
        string=re.sub(old,new,string)
    return string

string1="234"
string2="a2b3c4"
string3="abc"
string4="#2a$#b%c%561#"
print(replace_char(string1))
print(replace_char(string2))
print(replace_char(string3))
print(replace_char(string4))

###
###

####


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [75]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure

def display_dash_board(marks, students):
    marks_to_students_zipped = list(zip(marks, students))        ## zip() method - will bind together corresponding elements of students and marks
    print("Zipped Mark List:",marks_to_students_zipped)          ##print the zipped output
    marks_to_students_zipped.sort(key=lambda item: item[0])      ##selecting [0] as it will sorted on marks
    top_5_students = least_5_students = marks_to_students_zipped ##define top5 and least5 as marks to studemts zipped sorted list
    if len(marks_to_students_zipped) > 5:                        ##if there are more than 5 elements in zipped list     
        top_5_students = marks_to_students_zipped[:-6: -1]       ##slicing the top 5 marks as the list is sorted on marks
        least_5_students = marks_to_students_zipped[:5]          ##slicing the least 5 marks from the list
    students_between_25_and_75_percentile = marks_to_students_zipped[math.ceil(0.25 * len(marks_to_students_zipped)):
                                                                     math.floor(0.75 * len(marks_to_students_zipped))] ##slicing is done from 25th
                                                                                                                       ##to 75th percentile which is
                                                                                                                       ##outside of the if condition
    return top_5_students, least_5_students, students_between_25_and_75_percentile ##return the three outputs

Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
display_dash_board(Marks, Students)

Zipped Mark List: [(45, 'student1'), (78, 'student2'), (12, 'student3'), (14, 'student4'), (48, 'student5'), (43, 'student6'), (47, 'student7'), (98, 'student8'), (35, 'student9'), (80, 'student10')]


([(98, 'student8'),
  (80, 'student10'),
  (78, 'student2'),
  (48, 'student5'),
  (47, 'student7')],
 [(12, 'student3'),
  (14, 'student4'),
  (35, 'student9'),
  (43, 'student6'),
  (45, 'student1')],
 [(43, 'student6'), (45, 'student1'), (47, 'student7'), (48, 'student5')])

<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [67]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    # write your code here
    closest_points=[]                                                           ##list to append closest points
    final_list=[]                                                               ##list of output
    for point in S:                                                             ##looping through the given set of points
        ##numerator and denominator in the cosine function to find the closest point.
        denominator = math.sqrt((point[0] ** 2) + (point[1] ** 2)) * math.sqrt((P[0] ** 2) + (P[1] ** 2))
        numerator = point[0] * P[0] + point[1] * P[1]
        if denominator!=0:                                                      ##if the denominator is not equal to 0, this operation is possible
            cosine_distance_for_this_point = math.acos(numerator / denominator) ##cosine distance for the looped point
            closest_points.append((cosine_distance_for_this_point, point))      ##appending the closest point to the closest point list
    for item in sorted(closest_points, key=lambda x: x[0])[:5]:
        final_list.append(item[1])                                              ## append the closest points to the final list
    return final_list                                                           ## its list of tuples

S = [(1, 2), (3, 4), (-1, 1), (6, -7), (0, 6), (-5, -8), (-1, -1), (6, 0), (1, -1)]
P = (3, -4)
points = closest_points_to_p(S, P)
print(points)                                                                   ##print the returned values

[(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1)]


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [58]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
import math

def i_am_the_one(red, blue, line):  ##function will take red,blue and line arguments
    sign_of_equation_with_red_point_tuple = -1  ##Initiate a variable sign_of_equation_with_red_point_tuple to be minus 1 (-1)
    if eval(line.replace('x', '*%s' % red[0][0]).replace('y', '*%s' % red[0][1])) > 0:  ##Take the first tuple of the Red_side list 
                                                                                        ##(i.e. red[0][0] and red[0][1] ) and replace then into the Equation.
                                                                                        ##If sign of Equation becomes positive with this, then change 
                                                                                        ##sign_of_equation_with_red_point_tuple to be plus 1 ( 1 )
        sign_of_equation_with_red_point_tuple = 1
        
    ##assuming sign_of_equation_with_red_point_tuple to be plus one ( 1 )
    for red_point in red:  ##looping through the red point
        if sign_of_equation_with_red_point_tuple == 1 and eval(line.replace('x', '*%s' % red_point[0]).replace('y', '*%s' % red_point[1])) < 0:
                         ##One by one, check for all the Red side's tuples (points) - 
                         ##if Equation sign becomes negative for any point > 
                         ##That means that single point is on the other side of the Line Equation.
            return "NO"  ##So in that case, then return 'NO' from the function.
        if sign_of_equation_with_red_point_tuple == -1 and eval(line.replace('x', '*%s' % red_point[0]).replace('y', '*%s' % red_point[1])) > 0:
            ##in the next step, assuming sign_of_equation_with_red_point_tuple to be negaive 1 (-1), do the below step
            ##check for all the Red side's tuples (points) - 
            ##if Equation sign becomes positive for any point > That means that single point is on the other side of the Line Equation
            return "NO"  ##So in that case, then return 'NO' from the function.
    # Now the same set of two traversal for the blue-points tuples
    sign_of_equation_with_blue_point_tuple = -1 * sign_of_equation_with_red_point_tuple ####Initiate a variable sign_of_equation_with_blue_point_tuple to be minus 1 (-1)
    for blue_point in blue:  ##similarly looping through the blue points
        if sign_of_equation_with_blue_point_tuple == 1 and eval(line.replace('x', '*%s' % blue_point[0]).replace('y', '*%s' % blue_point[1])) < 0:
                         ##One by one, check for all the Blue side's tuples (points) - 
                         ##if Equation sign becomes negative for any point > 
                         ##That means that single point is on the other side of the Line Equation.
            return "NO"  ##So in that case, then return 'NO' from the function.
        if sign_of_equation_with_blue_point_tuple == -1 and eval(line.replace('x', '*%s' % blue_point[0]).replace('y', '*%s' % blue_point[1])) > 0:
            ##in the next step, assuming sign_of_equation_with_red_point_tuple to be negaive 1 (-1), do the below step
            ##check for all the Red side's tuples (points) - 
            ##if Equation sign becomes positive for any point > That means that single point is on the other side of the Line Equation
            return "NO"  ##So in that case, then return 'NO' from the function.
        return "YES"  ##And if none of the above 4 steps returns a 'NO' ans, then finally return 'YES' from the function.


Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]


for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) # the returned value   
            

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [68]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def curve_smoothing(string):
    index_of_non_empty_cells_list = []                      ##list to store non empty cell from the string
    ##split the String by ","
    split_string = string.split(',')
    print("Splitted String: ",split_string)
    
    for idx in range(len(split_string)):                    ##looping through the length of the split string
        if split_string[idx] != '_':                        ##if the looped index is not equal to "_"
            index_of_non_empty_cells_list.append(idx)       ##append that index to the index of non empty cells list
            
    index_of_non_empty_cells_list.append(len(split_string) - 1)  ### The total index-length of the original list
    print("Index of NOn Empty Cell: ",index_of_non_empty_cells_list)  ##print the non-emptyy index
    
    ##loop over index_of_non_empty_cells_list to modify the original list by filing up empty_cells
    position_to_start = 0 ##initialize the position to start
    
    for element in index_of_non_empty_cells_list: ##looping through the non_empty_cell_list of index
        # Wherever, there is a missing values, add the immediately proceeding value
        # and the immediately next available value and then divide it by the number of missing values.
        # initiate a variable to 'cumulative_sum_prev_and_next_value' to hold the cumulative sum of available (i.e. non-empty) cells
        cumulative_sum_prev_and_next_value = int(split_string[element]) if split_string[element] != '_' else 0
        cumulative_sum_prev_and_next_value += int(split_string[position_to_start]) if split_string[
                                              position_to_start] != '_' and position_to_start != element else 0
        # print(cumulative_sum_prev_and_next_value) Now divide the cumulative_sum of prev and next value by the number of missing values
        print("Cumulative Sum of Previous and Next Value:",cumulative_sum_prev_and_next_value)
        integer_to_replace_each_previous_empty_cell = cumulative_sum_prev_and_next_value // (element - position_to_start + 1)
        print("integer_to_replace_each_previous_empty_cell value is ", integer_to_replace_each_previous_empty_cell)
        
        # For the first loop it will give me 10 which is what I will replace each emtpy value with
        # And now modify the original list by replacing the empty cells with the above
        # value i.e.  integer_to_replace_each_previous_empty_cell
        
        split_string = [integer_to_replace_each_previous_empty_cell if position_to_start <= x <= element else split_string[x] for x
                                                                                                            in range(len(split_string))]
        
        print("Splitted String: ",split_string)
        print("element: %s cumulative_sum_prev_and_next_value: %s  split_string: %s" %(element, cumulative_sum_prev_and_next_value, split_string))
        # After original list has been updated by filling up the empty cells
        # now update the starting position for the next loop
        position_to_start = element
        
    return split_string

S1=  "_,_,_,24"
print("Result One:",curve_smoothing(S1),"\n")
S2="40,_,_,_,60"
print("Result Two:",curve_smoothing(S2),"\n")
S3="80,_,_,_,_"
print("Result Three",curve_smoothing(S3),"\n")
S4="_,_,30,_,_,_,50,_,_"
print("Result Four",curve_smoothing(S4),"\n")

Splitted String:  ['_', '_', '_', '24']
Index of NOn Empty Cell:  [3, 3]
Cumulative Sum of Previous and Next Value: 24
integer_to_replace_each_previous_empty_cell value is  6
Splitted String:  [6, 6, 6, 6]
element: 3 cumulative_sum_prev_and_next_value: 24  split_string: [6, 6, 6, 6]
Cumulative Sum of Previous and Next Value: 6
integer_to_replace_each_previous_empty_cell value is  6
Splitted String:  [6, 6, 6, 6]
element: 3 cumulative_sum_prev_and_next_value: 6  split_string: [6, 6, 6, 6]
Result One: [6, 6, 6, 6] 

Splitted String:  ['40', '_', '_', '_', '60']
Index of NOn Empty Cell:  [0, 4, 4]
Cumulative Sum of Previous and Next Value: 40
integer_to_replace_each_previous_empty_cell value is  40
Splitted String:  [40, '_', '_', '_', '60']
element: 0 cumulative_sum_prev_and_next_value: 40  split_string: [40, '_', '_', '_', '60']
Cumulative Sum of Previous and Next Value: 100
integer_to_replace_each_previous_empty_cell value is  20
Splitted String:  [20, 20, 20, 20, 20]
element: 4 cumula

<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
+  1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
+  2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [20]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
dictionary1 = {
'F1S1': 0,
'F2S1': 0,
'F3S1': 0,
'F4S1': 0,
'F5S1': 0,
'F1S2': 0,
'F2S2': 0,
'F3S2': 0,
'F4S2': 0,
'F5S2': 0,
'F1S3': 0,
'F2S3': 0,
'F3S3': 0,
'F4S3': 0,
'F5S3': 0,
}

dictionary2 = {
'S1': 0,
'S2': 0,
'S3': 0
}



# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
    for i in range(len(A)):
        k = A[i][0] + A[i][1]
        dictionary1[k] += 1
        dictionary2[A[i][1]] += 1
A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)
print("\n=============A====================\n")
print('Probability of P(F=F1|S==S1)', (dictionary1['F1S1']/dictionary2['S1']))
print('Probability of P(F=F1|S==S2)', (dictionary1['F1S2']/dictionary2['S2']))
print('Probability of P(F=F1|S==S3)', (dictionary1['F1S3']/dictionary2['S3']))
print("\n=============B====================\n")
print('Probability of P(F=F2|S==S1)', (dictionary1['F2S1']/dictionary2['S1']))
print('Probability of P(F=F2|S==S2)', (dictionary1['F2S2']/dictionary2['S2']))
print('Probability of P(F=F2|S==S3)', (dictionary1['F2S3']/dictionary2['S3']))
print("\n=============C====================\n")
print('Probability of P(F=F3|S==S1)', (dictionary1['F3S1']/dictionary2['S1']))
print('Probability of P(F=F3|S==S2)', (dictionary1['F3S2']/dictionary2['S2']))
print('Probability of P(F=F3|S==S3)', (dictionary1['F3S3']/dictionary2['S3']))
print("\n=============D====================\n")
print('Probability of P(F=F4|S==S1)', (dictionary1['F4S1']/dictionary2['S1']))
print('Probability of P(F=F4|S==S2)', (dictionary1['F4S2']/dictionary2['S2']))
print('Probability of P(F=F4|S==S3)', (dictionary1['F4S3']/dictionary2['S3']))
print("\n=============E====================\n")
print('Probability of P(F=F5|S==S1)', (dictionary1['F5S1']/dictionary2['S1']))
print('Probability of P(F=F5|S==S2)', (dictionary1['F5S2']/dictionary2['S2']))
print('Probability of P(F=F5|S==S3)', (dictionary1['F5S3']/dictionary2['S3']))


=============A====================

Probability of P(F=F1|S==S1) 0.25
Probability of P(F=F1|S==S2) 0.3333333333333333
Probability of P(F=F1|S==S3) 0.0

=============B====================

Probability of P(F=F2|S==S1) 0.25
Probability of P(F=F2|S==S2) 0.3333333333333333
Probability of P(F=F2|S==S3) 0.3333333333333333

=============C====================

Probability of P(F=F3|S==S1) 0.0
Probability of P(F=F3|S==S2) 0.3333333333333333
Probability of P(F=F3|S==S3) 0.3333333333333333

=============D====================

Probability of P(F=F4|S==S1) 0.25
Probability of P(F=F4|S==S2) 0.0
Probability of P(F=F4|S==S3) 0.3333333333333333

=============E====================

Probability of P(F=F5|S==S1) 0.25
Probability of P(F=F5|S==S2) 0.0
Probability of P(F=F5|S==S3) 0.0


In [73]:
from fractions import Fraction

def compute_conditional_probability(A):
    # From the given 2-D Matrix A
    # Set a dictionary containing the count of all the F and S together
    # This dictionary will have as many elements as the given Matrix A
    dictionary_f_intersection_s=dict()                      ## Initiate a dictionary with key value pair
    for item_list in A:                                     ## looping through the List A
        dict_key = str(item_list[0])+str(item_list[1])      ## combine first element and second element from item_lists
        #print(dict_key)
        dictionary_f_intersection_s[dict_key]=0             ## assign 0 to every combination
        #print("Intersection Combinations from Every Element in the List:",dictionary_f_intersection_s)
        
    # Set a dictionary containing the count of all the S only
    dictionary_s=dict()                                     ## initialize dictionary_s with key value pair
    for item in A:                                          ## looping through the list A
        dict_key=str(item[1])                               ## choosing the second element from the iteration 
        #print(kict_key)                                                                         
        dictionary_s[dict_key]=0                            ## assign the 0 to every key contains
        #print(dictionary_s)
    
    for i in range(len(A)):
        f_intersection_s_key=A[i][0]+A[i][1]                 ## f intersection s, looping through the list A, combining the first and second element
        #print(f_intersection_s_key)                         ## print the keys
        dictionary_f_intersection_s[f_intersection_s_key]+=1 ## updating the dictionary_f_intersection_s dictionary with keys
        #print(dictionary_f_intersection_s)                  ## print the dictionary_f_intersection_s
        s_key=A[i][1]                                        ## s_keys from A, taking the key value as second value in the every iterated values
        #print(s_key)                                        ## print the keys
        dictionary_s[s_key]+=1                               ## updating the dictinary_s with s_keys
        #print(dictionary_s)                                 ## print the dictionary_s
        
    idx=97
    print('{0:c}. P(F=F1|S==S1)={F1S1}/{S1}, P(F=F1|S==S2)={F1S2}/{S2}, P(F=F1|S==S3)={F1S3}/{S3}'.format(idx,
                                F1S1=dictionary_f_intersection_s.get('F1S1',0), S1=dictionary_s['S1'],
                                F1S2=dictionary_f_intersection_s.get('F1S2',0), S2=dictionary_s['S2'],
                                F1S3=dictionary_f_intersection_s.get('F1S3',0), S3=dictionary_s['S3']))

    print('{0:c}. P(F=F2|S==S1)={F2S1}/{S1}, P(F=F2|S==S2)={F2S2}/{S2}, P(F=F2|S==S3)={F2S3}/{S3}'.format(idx+1,
                                F2S1=dictionary_f_intersection_s.get('F2S1',0), S1=dictionary_s['S1'],
                                F2S2=dictionary_f_intersection_s.get('F2S2',0), S2=dictionary_s['S2'],
                                F2S3=dictionary_f_intersection_s.get('F2S3',0), S3=dictionary_s['S3']))

    print('{0:c}. P(F=F3|S==S1)={F3S1}/{S1}, P(F=F3|S==S2)={F3S2}/{S2}, P(F=F3|S==S3)={F3S3}/{S3}'.format(idx+2,
                                F3S1=dictionary_f_intersection_s.get('F3S1',0), S1=dictionary_s['S1'],
                                F3S2=dictionary_f_intersection_s.get('F3S2',0), S2=dictionary_s['S2'],                                                                          
                                F3S3=dictionary_f_intersection_s.get('F3S3',0), S3=dictionary_s['S3']))

    print('{0:c}. P(F=F4|S==S1)={F4S1}/{S1}, P(F=F4|S==S2)={F4S2}/{S2}, P(F=F4|S==S3)={F4S3}/{S3}'.format(idx+3,
                                F4S1=dictionary_f_intersection_s.get('F4S1',0), S1=dictionary_s['S1'],
                                F4S2=dictionary_f_intersection_s.get('F4S2',0), S2=dictionary_s['S2'],
                                F4S3=dictionary_f_intersection_s.get('F4S3',0), S3=dictionary_s['S3']))

    print('{0:c}. P(F=F5|S==S1)={F5S1}/{S1}, P(F=F5|S==S2)={F5S2}/{S2}, P(F=F5|S==S3)={F5S3}/{S3}'.format(idx+4,
                                F5S1=dictionary_f_intersection_s.get('F5S1',0), S1=dictionary_s['S1'],
                                F5S2=dictionary_f_intersection_s.get('F5S2',0), S2=dictionary_s['S2'],
                                F5S3=dictionary_f_intersection_s.get('F5S3',0), S3=dictionary_s['S3']))
    

A = [['F1', 'S1'], ['F2', 'S2'], ['F3', 'S3'], ['F1', 'S2'], ['F2', 'S3'], ['F3', 'S2'], ['F2', 'S1'], ['F4', 'S1'],
     ['F4', 'S3'], ['F5', 'S1']]

compute_conditional_probability(A)

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [69]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    S1_unique_words_set=set(S1.split(" "))              ##split S1 by space and making a set of words
    print("S1 Unique Words: ",S1_unique_words_set)      ##print the S1 unique words
    S2_unique_words_set=set(S2.split(" "))              ##split S2 by space and making a set of words
    print("S2 Unique Words: ",S2_unique_words_set)      ##print the S2 unique words
    
    num_of_common_words=len(S1_unique_words_set.intersection(S2_unique_words_set))   ##taking intersection of words present in both S1 and S2, 
                                                                                     ##then taking the length of the list
    s1_words_not_in_s2 = S1_unique_words_set - S2_unique_words_set                   ##words that are only present in S1 but not in S2
    s2_words_not_in_s1 = S2_unique_words_set - S1_unique_words_set                   ##words that are only present in S2 but not in S1
    
    print('a. ', num_of_common_words)            ##num of common words
    print('b. ', list(s1_words_not_in_s2))       ##list of elements present in S1 but not in S2
    print('b. ', list(s2_words_not_in_s1))       ##list of elements present in S2 but not in S1

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
string_features(S1, S2)

S1 Unique Words:  {'F', 'only', 'first', 'the', 'will', '5', 'uniques', 'values', 'contain', 'column'}
S2 Unique Words:  {'only', 'the', 'will', '3', 'second', 'uniques', 'S', 'values', 'contain', 'column'}
a.  7
b.  ['F', 'first', '5']
b.  ['S', '3', 'second']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [72]:
from math import log
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def compute_log_loss(A):
    # your code
    ##initiate logistic loss
    logistic_loss=0
    for row in A:                                                          ##looping through the rows of A
        logistic_loss+=(row[0]*log(row[1],10)+(1-row[0])*log(1-row[1],10)) ##Computing the logistic loss and adding to logistic_loss
    log_loss=-1*logistic_loss/len(A)                                       ##logloss is calculated as the given formula.
    
    return log_loss                                                        ##return log_loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print('%.7f'%loss)                                                         ##print the output to 7 decimal point

0.4243099
